language: node_js
notifications:
  email: false
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc
node_js:
  - '6'
cache:
  yarn: true
before_install:
  - npm i -g codecov
  - pip install --user mkdocs
script:
  - yarn run lint
  - yarn run flow
  - yarn run cover-client
  - codecov
  - yarn run build
  - mkdocs build

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Push results to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn run semantic-release
